### ISSUE TITLE
[OOB] Green LED always turns on 

### ISSUE THREAD

**Issue by coisme** [ARMmbed/connected-lights-cloud#34]
I'm trying **_Connected Lights_** tutorial. At **_Added the code_** section in [**_Writing the software_**](https://cloud.test.mbed.com/docs/working/connecting/writing-the-software.html) page, I copied & pasted the source code into `main.cpp` file. Compilation succeeded and program ran. However, my LED always turns on green.

# My Environment

macOS High Sierra Version 10.13.5
Board: K64F
LED: Tri-color anode type

# Steps to reproduce this issue

1. Set up HW with tri-color anode type LED with following [this instruction page](https://cloud.test.mbed.com/docs/working/connecting/building-the-circuit.html).
1. Clone this repository
1. Change `led-type` to `TRICOLOR_ANODE` in `mbed_app.json`
1. Create `main.cpp` file and copy & paste the program in [this instruction page](https://cloud.test.mbed.com/docs/working/connecting/writing-the-software.html)
1. Compile, and run on K64F

# Inferred Cause

In `lightning-system-firmware/source/led.h`, `GROVE_CHAINABLE` and `TRICOLOR_ANODE` are not defined. Therefore the first `#if` block is compiled even if you specify `TRICOLOR_ANODE` in `mbed_app.json`, because the condition is `0 == 0`, true.

https://github.com/ARMmbed/connected-lights-cloud/blob/3c5cc5bd992fd2c1ef003e665878fa1e239b2d56/lighting-system-firmware/source/led.h#L4-L11

This causes configuration error.

**Comment by MarceloSalazar** [comment]
FYI @janjongboom

**Comment by janjongboom** [comment]
Landed.

**Comment by coisme** [comment]
Verified.
